USE viettalent_job_vacancy_db;

-- Demo accounts (admin + 12 employer users + 6 job seekers)
-- Default password for every demo account: password
INSERT INTO users (id, full_name, email, password_hash, role, status) VALUES
(1, 'System Administrator', 'admin@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'admin', 'active'),
(2, 'Demo Employer', 'employer@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'employer', 'active'),
(3, 'Demo Job Seeker', 'jobseeker@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'job_seeker', 'active'),
(4, 'Recruiter at SaiGon Digital', 'hr+saigondigital@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'employer', 'active'),
(5, 'Recruiter at Hanoi DataLab', 'hr+hanoidatalab@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'employer', 'active'),
(6, 'Recruiter at VinaCloud', 'hr+vinacloud@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'employer', 'active'),
(7, 'Recruiter at FinTrust Bank', 'hr+fintrustbank@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'employer', 'active'),
(8, 'Recruiter at EduSpark Vietnam', 'hr+edusparkvietnam@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'employer', 'active'),
(9, 'Recruiter at GreenLogix', 'hr+greenlogix@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'employer', 'active'),
(10, 'Recruiter at HealthFirst Clinics', 'hr+healthfirstclinics@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'employer', 'active'),
(11, 'Recruiter at PixelCraft Studio', 'hr+pixelcraftstudio@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'employer', 'active'),
(12, 'Recruiter at MekongTrade', 'hr+mekongtrade@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'employer', 'active'),
(13, 'Recruiter at UrbanRetail Group', 'hr+urbanretailgroup@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'employer', 'active'),
(14, 'Recruiter at QuantumAI Labs', 'hr+quantumailabs@viettalent.local', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'employer', 'active'),
(15, 'Le Minh Anh', 'minhanh.le@example.com', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'job_seeker', 'active'),
(16, 'Tran Quoc Bao', 'quocbao.tran@example.com', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'job_seeker', 'active'),
(17, 'Pham Hoai My', 'hoaimy.pham@example.com', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'job_seeker', 'active'),
(18, 'Vo Tan Phat', 'tanphat.vo@example.com', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'job_seeker', 'active'),
(19, 'Nguyen Bich Tram', 'bichtram.nguyen@example.com', '$2y$10$Mu7FYllgENX7zogxCRDrdu5.KWd3CrZrPRzS4BGaYu70zVHq/kM5m', 'job_seeker', 'active');

INSERT INTO employer_profiles (id, user_id, company_name, company_website, company_description) VALUES
(1, 2, 'TechViet Solutions', 'https://techviet.example.com', 'Award-winning software house focused on enterprise web platforms.'),
(2, 4, 'SaiGon Digital', 'https://sgdigital.example.com', 'Digital agency specialising in e-commerce and marketing automation.'),
(3, 5, 'Hanoi DataLab', 'https://hndatalab.example.com', 'Data engineering and analytics consultancy serving APAC clients.'),
(4, 6, 'VinaCloud', 'https://vinacloud.example.com', 'Managed cloud and DevOps provider for high-growth startups.'),
(5, 7, 'FinTrust Bank', 'https://fintrust.example.com', 'Modern retail bank investing in mobile-first customer experiences.'),
(6, 8, 'EduSpark Vietnam', 'https://eduspark.example.com', 'EdTech platform connecting learners with vetted private tutors.'),
(7, 9, 'GreenLogix', 'https://greenlogix.example.com', 'Logistics and supply-chain technology company.'),
(8, 10, 'HealthFirst Clinics', 'https://healthfirst.example.com', 'Network of urban primary-care clinics across Vietnam.'),
(9, 11, 'PixelCraft Studio', 'https://pixelcraft.example.com', 'Creative studio specialising in branding, UI and motion design.'),
(10, 12, 'MekongTrade', 'https://mekongtrade.example.com', 'B2B import/export marketplace for agricultural goods.'),
(11, 13, 'UrbanRetail Group', 'https://urbanretail.example.com', 'Multi-brand retailer with stores across major Vietnamese cities.'),
(12, 14, 'QuantumAI Labs', 'https://quantumai.example.com', 'Applied AI research lab focused on computer vision.');

INSERT INTO job_seeker_profiles (id, user_id) VALUES
(1, 3),
(2, 15),
(3, 16),
(4, 17),
(5, 18),
(6, 19);

INSERT INTO job_titles (name) VALUES
('Software Engineer'),
('Frontend Developer'),
('Backend Developer'),
('Full Stack Developer'),
('Mobile Developer'),
('DevOps Engineer'),
('QA Engineer'),
('Data Analyst'),
('Data Engineer'),
('Data Scientist'),
('Product Manager'),
('Project Manager'),
('Business Analyst'),
('UI/UX Designer'),
('Graphic Designer'),
('Marketing Specialist'),
('Digital Marketing Manager'),
('Content Writer'),
('Sales Executive'),
('Customer Support Specialist'),
('HR Specialist'),
('Accountant'),
('Financial Analyst'),
('Network Administrator'),
('System Administrator'),
('Cybersecurity Analyst'),
('Cloud Engineer'),
('Machine Learning Engineer'),
('Technical Writer'),
('Solutions Architect');

INSERT INTO job_categories (name) VALUES
('Information Technology'),
('Software Development'),
('Data & Analytics'),
('Design & Creative'),
('Marketing & Advertising'),
('Sales & Business Development'),
('Customer Service'),
('Human Resources'),
('Finance & Accounting'),
('Operations'),
('Engineering'),
('Education'),
('Healthcare');

INSERT INTO industries (name) VALUES
('Software'),
('E-commerce'),
('Banking & Finance'),
('Education'),
('Manufacturing'),
('Healthcare'),
('Telecommunications'),
('Logistics'),
('Real Estate'),
('Retail'),
('Hospitality'),
('Media & Entertainment');

INSERT INTO employment_types (name) VALUES
('Full-time'),
('Part-time'),
('Contract'),
('Internship'),
('Freelance');

INSERT INTO job_levels (name) VALUES
('Junior'),
('Mid'),
('Senior'),
('Lead'),
('Manager');

INSERT INTO salary_ranges (label, min_salary, max_salary, currency) VALUES
('Under 500 USD', 0, 499, 'USD'),
('500-800 USD', 500, 800, 'USD'),
('800-1200 USD', 800, 1200, 'USD'),
('1200-1800 USD', 1200, 1800, 'USD'),
('1800-2500 USD', 1800, 2500, 'USD'),
('2500-3500 USD', 2500, 3500, 'USD'),
('3500-5000 USD', 3500, 5000, 'USD'),
('5000+ USD', 5000, NULL, 'USD'),
('Negotiable', 0, NULL, 'USD');

INSERT INTO salary_types (name) VALUES
('Gross'),
('Net');

INSERT INTO skills (name) VALUES
('PHP'),
('MySQL'),
('JavaScript'),
('TypeScript'),
('HTML'),
('CSS'),
('SCSS'),
('Vue.js'),
('React'),
('Angular'),
('Node.js'),
('Express.js'),
('Java'),
('Spring Boot'),
('Python'),
('Django'),
('Flask'),
('C#'),
('.NET'),
('Go'),
('Rust'),
('Ruby on Rails'),
('Swift'),
('Kotlin'),
('Flutter'),
('React Native'),
('Docker'),
('Kubernetes'),
('AWS'),
('Azure'),
('Google Cloud'),
('Linux'),
('Git'),
('CI/CD'),
('SQL'),
('PostgreSQL'),
('MongoDB'),
('Redis'),
('Tableau'),
('Power BI'),
('Excel'),
('R'),
('SAS'),
('Figma'),
('Adobe Photoshop'),
('Adobe Illustrator'),
('Sketch'),
('Communication'),
('Problem Solving'),
('Teamwork'),
('Leadership'),
('English'),
('SEO'),
('Google Ads'),
('Content Writing'),
('Copywriting');

INSERT INTO proficiency_levels (name) VALUES
('Beginner'),
('Intermediate'),
('Advanced'),
('Expert');

INSERT INTO degree_levels (name) VALUES
('High School'),
('Associate Degree'),
('Bachelor Degree'),
('Master Degree'),
('PhD');

INSERT INTO experience_levels (name) VALUES
('No experience'),
('Less than 1 year'),
('1-2 years'),
('3-5 years'),
('5+ years'),
('8+ years');

INSERT INTO work_arrangements (name) VALUES
('Onsite'),
('Remote'),
('Hybrid');

INSERT INTO countries (id, name) VALUES
(1, 'Vietnam'),
(2, 'Singapore'),
(3, 'United States'),
(4, 'Japan'),
(5, 'Germany');

INSERT INTO cities (id, country_id, name) VALUES
(1, 1, 'Ho Chi Minh City'),
(2, 1, 'Ha Noi'),
(3, 1, 'Da Nang'),
(4, 1, 'Hai Phong'),
(5, 1, 'Can Tho'),
(6, 1, 'Bien Hoa'),
(7, 1, 'Nha Trang'),
(8, 2, 'Singapore'),
(9, 3, 'San Francisco'),
(10, 3, 'New York'),
(11, 3, 'Austin'),
(12, 4, 'Tokyo'),
(13, 4, 'Osaka'),
(14, 5, 'Berlin'),
(15, 5, 'Munich');

INSERT INTO districts (city_id, name) VALUES
(1, 'District 1'),
(1, 'District 3'),
(1, 'District 7'),
(1, 'Binh Thanh'),
(1, 'Phu Nhuan'),
(1, 'Tan Binh'),
(1, 'Thu Duc'),
(2, 'Ba Dinh'),
(2, 'Cau Giay'),
(2, 'Dong Da'),
(2, 'Hai Ba Trung'),
(2, 'Hoan Kiem'),
(2, 'Hoang Mai'),
(3, 'Hai Chau'),
(3, 'Thanh Khe'),
(3, 'Son Tra'),
(3, 'Ngu Hanh Son'),
(4, 'Le Chan'),
(4, 'Ngo Quyen'),
(5, 'Ninh Kieu'),
(5, 'Cai Rang'),
(6, 'Tam Hoa'),
(7, 'Loc Tho'),
(7, 'Vinh Hai'),
(8, 'Central'),
(8, 'Jurong'),
(8, 'Tampines'),
(9, 'Downtown'),
(9, 'SoMa'),
(10, 'Manhattan'),
(10, 'Brooklyn'),
(11, 'Downtown'),
(12, 'Shinjuku'),
(12, 'Shibuya'),
(13, 'Umeda'),
(14, 'Mitte'),
(14, 'Kreuzberg'),
(15, 'Altstadt');

-- VietTalent branch offices (Google Maps embed)
INSERT INTO store_locations (name, address, city_id, phone, email, hours, latitude, longitude, map_query, status) VALUES
('VietTalent HQ', '268 Ly Thuong Kiet, District 10', 1, '+84 28 3864 7256', 'hello@viettalent.vn', 'Mon–Fri 08:30–18:00', 10.7728, 106.6588, '268 Ly Thuong Kiet, District 10, Ho Chi Minh City', 'active'),
('VietTalent Hanoi Office', '1 Dai Co Viet, Hai Ba Trung', 2, '+84 24 3868 4137', 'hanoi@viettalent.vn', 'Mon–Fri 08:30–18:00', 21.0066, 105.843, '1 Dai Co Viet, Hai Ba Trung, Hanoi', 'active'),
('VietTalent Da Nang Hub', '54 Nguyen Luong Bang, Lien Chieu', 3, '+84 236 3736 020', 'danang@viettalent.vn', 'Mon–Fri 08:30–18:00', 16.0735, 108.1497, '54 Nguyen Luong Bang, Lien Chieu, Da Nang', 'active'),
('VietTalent Singapore', '1 Raffles Place', 8, '+65 6438 1234', 'sg@viettalent.com', 'Mon–Fri 09:00–18:00', 1.284, 103.8512, '1 Raffles Place, Singapore', 'active');

-- 60 job vacancies (mix of active / inactive / removed)
INSERT INTO job_vacancies (id, employer_id, job_title_id, job_category_id, employment_type_id, industry_id, job_level_id, number_of_openings, country_id, city_id, district_id, work_arrangement_id, salary_range_id, salary_type_id, benefits, responsibilities, required_qualifications, preferred_skills, additional_notes, degree_level_id, experience_level_id, status, created_at) VALUES
(1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 13, 1, 1, 1, 'English / Japanese language courses subsidised, flexible working hours.', 'Mentor junior engineers and contribute to internal engineering blogs. Translate functional requirements into clean, well-tested code following the team coding standards. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Own the data pipeline from ingestion to visualisation, ensuring data quality.', 'Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Track record of shipping production-quality software in collaborative teams. Strong communication skills in English and Vietnamese (written and spoken).', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Experience with cloud platforms (AWS, GCP or Azure).', 'You will join a 6-person squad reporting to the Engineering Manager.', 1, 1, 'active', '2026-03-31 02:00:00'),
(2, 2, 8, 4, 1, 12, 2, 1, 1, 2, 11, 2, 2, 2, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Own the data pipeline from ingestion to visualisation, ensuring data quality. Mentor junior engineers and contribute to internal engineering blogs. Collaborate with marketing on multi-channel campaigns and performance tracking. Participate in code reviews, sprint planning, retrospectives and on-call rotations.', 'Solid understanding of OOP, algorithms, and modern web architecture. Track record of shipping production-quality software in collaborative teams. Strong communication skills in English and Vietnamese (written and spoken). Experience working in an Agile / Scrum delivery team.', 'Open-source contributions or technical writing. A portfolio of shipped products or design case studies.', 'Visa sponsorship considered for exceptional international candidates.', 2, 2, 'active', '2026-04-11 04:00:00'),
(3, 3, 15, 7, 1, 11, 3, 3, 2, 8, 26, 3, 3, 1, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Participate in code reviews, sprint planning, retrospectives and on-call rotations. Collaborate with marketing on multi-channel campaigns and performance tracking. Build, ship and maintain user-facing features in close collaboration with design and product. Mentor junior engineers and contribute to internal engineering blogs.', 'Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Solid understanding of OOP, algorithms, and modern web architecture. Track record of shipping production-quality software in collaborative teams. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL.', 'Knowledge of Docker, Kubernetes or other container tooling. Open-source contributions or technical writing.', 'Two technical interviews + final culture-fit conversation with the hiring manager.', 3, 3, 'active', '2026-04-28 09:00:00'),
(4, 4, 22, 10, 1, 10, 4, 2, 5, 14, 37, 1, 4, 2, 'English / Japanese language courses subsidised, flexible working hours.', 'Build, ship and maintain user-facing features in close collaboration with design and product. Mentor junior engineers and contribute to internal engineering blogs. Collaborate with marketing on multi-channel campaigns and performance tracking. Participate in code reviews, sprint planning, retrospectives and on-call rotations.', 'Track record of shipping production-quality software in collaborative teams. Experience working in an Agile / Scrum delivery team. Solid understanding of OOP, algorithms, and modern web architecture. Familiarity with REST APIs, version control (Git), and CI/CD pipelines.', 'Knowledge of Docker, Kubernetes or other container tooling. Open-source contributions or technical writing.', 'Relocation support available for candidates outside the city.', 4, 4, 'active', '2026-04-04 11:00:00'),
(5, 5, 29, 13, 1, 9, 5, 3, 5, 15, NULL, 2, 5, 1, '13th month salary + performance bonus, premium health insurance for employee + family.', 'Own the data pipeline from ingestion to visualisation, ensuring data quality. Investigate production incidents and propose long-term improvements. Mentor junior engineers and contribute to internal engineering blogs. Pair with senior engineers to design new modules and refactor legacy areas.', 'Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Solid understanding of OOP, algorithms, and modern web architecture. Track record of shipping production-quality software in collaborative teams. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL.', 'Open-source contributions or technical writing. Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'Relocation support available for candidates outside the city.', 5, 5, 'active', '2026-04-21 01:00:00'),
(6, 6, 6, 3, 1, 8, 1, 5, 1, 5, 20, 3, 6, 2, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Investigate production incidents and propose long-term improvements. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Pair with senior engineers to design new modules and refactor legacy areas. Own the data pipeline from ingestion to visualisation, ensuring data quality.', 'Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Experience working in an Agile / Scrum delivery team. Solid understanding of OOP, algorithms, and modern web architecture. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience.', 'Experience with cloud platforms (AWS, GCP or Azure). Knowledge of Docker, Kubernetes or other container tooling.', 'Relocation support available for candidates outside the city.', 1, 6, 'active', '2026-04-06 06:00:00'),
(7, 7, 13, 6, 1, 7, 2, 5, 1, 7, 24, 1, 7, 1, '13th month salary + performance bonus, premium health insurance for employee + family.', 'Own the data pipeline from ingestion to visualisation, ensuring data quality. Collaborate with marketing on multi-channel campaigns and performance tracking. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Build, ship and maintain user-facing features in close collaboration with design and product.', 'Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Strong communication skills in English and Vietnamese (written and spoken). Track record of shipping production-quality software in collaborative teams.', 'Open-source contributions or technical writing. Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'You will join a 6-person squad reporting to the Engineering Manager.', 2, 1, 'active', '2026-04-09 23:00:00'),
(8, 8, 20, 9, 1, 6, 3, 1, 3, 11, 32, 2, 8, 2, 'English / Japanese language courses subsidised, flexible working hours.', 'Collaborate with marketing on multi-channel campaigns and performance tracking. Build, ship and maintain user-facing features in close collaboration with design and product. Mentor junior engineers and contribute to internal engineering blogs. Participate in code reviews, sprint planning, retrospectives and on-call rotations.', 'Strong communication skills in English and Vietnamese (written and spoken). Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Track record of shipping production-quality software in collaborative teams. Solid understanding of OOP, algorithms, and modern web architecture.', 'Open-source contributions or technical writing. A portfolio of shipped products or design case studies.', 'You will join a 6-person squad reporting to the Engineering Manager.', 3, 2, 'active', '2026-04-01 22:00:00'),
(9, 9, 27, 12, 1, 5, 4, 1, 2, 8, NULL, 3, 9, 1, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Own the data pipeline from ingestion to visualisation, ensuring data quality. Translate functional requirements into clean, well-tested code following the team coding standards. Build, ship and maintain user-facing features in close collaboration with design and product. Collaborate with marketing on multi-channel campaigns and performance tracking.', 'Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Strong communication skills in English and Vietnamese (written and spoken). Solid understanding of OOP, algorithms, and modern web architecture. Track record of shipping production-quality software in collaborative teams.', 'A portfolio of shipped products or design case studies. Open-source contributions or technical writing.', 'Relocation support available for candidates outside the city.', 4, 3, 'active', '2026-04-19 17:00:00'),
(10, 10, 4, 2, 1, 4, 5, 1, 1, 5, 21, 1, 1, 2, 'English / Japanese language courses subsidised, flexible working hours.', 'Translate functional requirements into clean, well-tested code following the team coding standards. Build, ship and maintain user-facing features in close collaboration with design and product. Own the data pipeline from ingestion to visualisation, ensuring data quality. Pair with senior engineers to design new modules and refactor legacy areas.', 'Strong communication skills in English and Vietnamese (written and spoken). Track record of shipping production-quality software in collaborative teams. Solid understanding of OOP, algorithms, and modern web architecture. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience.', 'A portfolio of shipped products or design case studies. Experience with cloud platforms (AWS, GCP or Azure).', 'Visa sponsorship considered for exceptional international candidates.', 5, 4, 'active', '2026-04-16 07:00:00'),
(11, 11, 11, 5, 1, 3, 1, 5, 2, 8, 25, 2, 2, 1, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Pair with senior engineers to design new modules and refactor legacy areas. Build, ship and maintain user-facing features in close collaboration with design and product. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Mentor junior engineers and contribute to internal engineering blogs.', 'Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Solid understanding of OOP, algorithms, and modern web architecture. Track record of shipping production-quality software in collaborative teams.', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Open-source contributions or technical writing.', 'Two technical interviews + final culture-fit conversation with the hiring manager.', 1, 5, 'active', '2026-04-10 11:00:00'),
(12, 12, 18, 8, 1, 2, 2, 2, 1, 1, 7, 3, 3, 2, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Collaborate with marketing on multi-channel campaigns and performance tracking. Drive the delivery of structured analytics dashboards for business stakeholders. Translate functional requirements into clean, well-tested code following the team coding standards. Own the data pipeline from ingestion to visualisation, ensuring data quality.', 'Strong communication skills in English and Vietnamese (written and spoken). Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Experience working in an Agile / Scrum delivery team.', 'Knowledge of Docker, Kubernetes or other container tooling. Open-source contributions or technical writing.', 'Relocation support available for candidates outside the city.', 2, 6, 'active', '2026-04-04 05:00:00'),
(13, 1, 25, 11, 1, 1, 3, 3, 1, 3, 16, 1, 4, 1, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Build, ship and maintain user-facing features in close collaboration with design and product. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Collaborate with marketing on multi-channel campaigns and performance tracking. Drive the delivery of structured analytics dashboards for business stakeholders.', 'Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Solid understanding of OOP, algorithms, and modern web architecture. Track record of shipping production-quality software in collaborative teams. Familiarity with REST APIs, version control (Git), and CI/CD pipelines.', 'Knowledge of Docker, Kubernetes or other container tooling. Open-source contributions or technical writing.', 'You will join a 6-person squad reporting to the Engineering Manager.', 3, 1, 'active', '2026-04-10 22:00:00'),
(14, 2, 2, 1, 1, 12, 4, 3, 1, 1, 1, 2, 5, 2, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Drive the delivery of structured analytics dashboards for business stakeholders. Translate functional requirements into clean, well-tested code following the team coding standards. Collaborate with marketing on multi-channel campaigns and performance tracking. Mentor junior engineers and contribute to internal engineering blogs.', 'Strong communication skills in English and Vietnamese (written and spoken). Solid understanding of OOP, algorithms, and modern web architecture. Track record of shipping production-quality software in collaborative teams. Familiarity with REST APIs, version control (Git), and CI/CD pipelines.', 'A portfolio of shipped products or design case studies. Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'Take-home assignment provided after the screening round.', 4, 2, 'active', '2026-04-23 12:00:00'),
(15, 3, 9, 4, 1, 11, 5, 1, 2, 8, NULL, 3, 6, 1, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Translate functional requirements into clean, well-tested code following the team coding standards. Build, ship and maintain user-facing features in close collaboration with design and product. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Mentor junior engineers and contribute to internal engineering blogs.', 'Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Solid understanding of OOP, algorithms, and modern web architecture. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL.', 'Experience with cloud platforms (AWS, GCP or Azure). A portfolio of shipped products or design case studies.', 'Take-home assignment provided after the screening round.', 5, 3, 'active', '2026-04-14 23:00:00'),
(16, 4, 16, 7, 1, 10, 1, 1, 1, 3, 14, 1, 7, 2, 'Equity / stock options for senior hires, paid parental leave, generous PTO.', 'Participate in code reviews, sprint planning, retrospectives and on-call rotations. Mentor junior engineers and contribute to internal engineering blogs. Investigate production incidents and propose long-term improvements. Collaborate with marketing on multi-channel campaigns and performance tracking.', 'Solid understanding of OOP, algorithms, and modern web architecture. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience.', 'Open-source contributions or technical writing. Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'Visa sponsorship considered for exceptional international candidates.', 1, 4, 'active', '2026-04-05 01:00:00'),
(17, 5, 23, 10, 1, 9, 2, 5, 3, 11, NULL, 2, 8, 1, 'English / Japanese language courses subsidised, flexible working hours.', 'Collaborate with marketing on multi-channel campaigns and performance tracking. Build, ship and maintain user-facing features in close collaboration with design and product. Own the data pipeline from ingestion to visualisation, ensuring data quality. Drive the delivery of structured analytics dashboards for business stakeholders.', 'Track record of shipping production-quality software in collaborative teams. Experience working in an Agile / Scrum delivery team. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Familiarity with REST APIs, version control (Git), and CI/CD pipelines.', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Experience with cloud platforms (AWS, GCP or Azure).', 'Take-home assignment provided after the screening round.', 2, 5, 'active', '2026-04-22 11:00:00'),
(18, 6, 30, 13, 1, 8, 3, 1, 1, 1, 7, 3, 9, 2, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Mentor junior engineers and contribute to internal engineering blogs. Drive the delivery of structured analytics dashboards for business stakeholders. Investigate production incidents and propose long-term improvements. Collaborate with marketing on multi-channel campaigns and performance tracking.', 'Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Solid understanding of OOP, algorithms, and modern web architecture. Strong communication skills in English and Vietnamese (written and spoken). Bachelor degree in Computer Science, Information Systems, or equivalent practical experience.', 'Knowledge of Docker, Kubernetes or other container tooling. Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'Relocation support available for candidates outside the city.', 3, 6, 'active', '2026-04-07 05:00:00'),
(19, 7, 7, 3, 1, 7, 4, 1, 1, 5, 21, 1, 1, 1, '13th month salary + performance bonus, premium health insurance for employee + family.', 'Drive the delivery of structured analytics dashboards for business stakeholders. Collaborate with marketing on multi-channel campaigns and performance tracking. Pair with senior engineers to design new modules and refactor legacy areas. Build, ship and maintain user-facing features in close collaboration with design and product.', 'Track record of shipping production-quality software in collaborative teams. Solid understanding of OOP, algorithms, and modern web architecture. Strong communication skills in English and Vietnamese (written and spoken). Bachelor degree in Computer Science, Information Systems, or equivalent practical experience.', 'A portfolio of shipped products or design case studies. Open-source contributions or technical writing.', 'Visa sponsorship considered for exceptional international candidates.', 4, 1, 'active', '2026-04-01 19:00:00'),
(20, 8, 14, 6, 1, 6, 5, 2, 1, 1, NULL, 2, 2, 2, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Translate functional requirements into clean, well-tested code following the team coding standards. Build, ship and maintain user-facing features in close collaboration with design and product. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Collaborate with marketing on multi-channel campaigns and performance tracking.', 'Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Experience working in an Agile / Scrum delivery team.', 'Knowledge of Docker, Kubernetes or other container tooling. A portfolio of shipped products or design case studies.', 'Relocation support available for candidates outside the city.', 5, 2, 'active', '2026-04-23 10:00:00'),
(21, 9, 21, 9, 1, 5, 1, 2, 1, 6, 22, 3, 3, 1, 'English / Japanese language courses subsidised, flexible working hours.', 'Collaborate with marketing on multi-channel campaigns and performance tracking. Mentor junior engineers and contribute to internal engineering blogs. Investigate production incidents and propose long-term improvements. Own the data pipeline from ingestion to visualisation, ensuring data quality.', 'Strong communication skills in English and Vietnamese (written and spoken). Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Track record of shipping production-quality software in collaborative teams.', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Experience with cloud platforms (AWS, GCP or Azure).', 'Visa sponsorship considered for exceptional international candidates.', 1, 3, 'active', '2026-04-08 09:00:00'),
(22, 10, 28, 12, 1, 4, 2, 1, 1, 4, NULL, 1, 4, 2, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Pair with senior engineers to design new modules and refactor legacy areas. Build, ship and maintain user-facing features in close collaboration with design and product. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Mentor junior engineers and contribute to internal engineering blogs.', 'Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Track record of shipping production-quality software in collaborative teams. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Experience working in an Agile / Scrum delivery team.', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Open-source contributions or technical writing.', 'You will join a 6-person squad reporting to the Engineering Manager.', 2, 4, 'active', '2026-04-17 16:00:00'),
(23, 11, 5, 2, 1, 3, 3, 5, 1, 4, 19, 2, 5, 1, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Participate in code reviews, sprint planning, retrospectives and on-call rotations. Investigate production incidents and propose long-term improvements. Build, ship and maintain user-facing features in close collaboration with design and product. Pair with senior engineers to design new modules and refactor legacy areas.', 'Strong communication skills in English and Vietnamese (written and spoken). Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Track record of shipping production-quality software in collaborative teams.', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Open-source contributions or technical writing.', 'You will join a 6-person squad reporting to the Engineering Manager.', 3, 5, 'active', '2026-04-12 07:00:00'),
(24, 12, 12, 5, 1, 2, 4, 2, 2, 8, 25, 3, 6, 2, '13th month salary + performance bonus, premium health insurance for employee + family.', 'Investigate production incidents and propose long-term improvements. Translate functional requirements into clean, well-tested code following the team coding standards. Own the data pipeline from ingestion to visualisation, ensuring data quality. Collaborate with marketing on multi-channel campaigns and performance tracking.', 'Solid understanding of OOP, algorithms, and modern web architecture. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Experience working in an Agile / Scrum delivery team. Track record of shipping production-quality software in collaborative teams.', 'A portfolio of shipped products or design case studies. Open-source contributions or technical writing.', 'Two technical interviews + final culture-fit conversation with the hiring manager.', 4, 6, 'active', '2026-04-12 23:00:00'),
(25, 1, 19, 8, 1, 1, 5, 3, 1, 7, 23, 1, 7, 1, 'Equity / stock options for senior hires, paid parental leave, generous PTO.', 'Own the data pipeline from ingestion to visualisation, ensuring data quality. Investigate production incidents and propose long-term improvements. Translate functional requirements into clean, well-tested code following the team coding standards. Pair with senior engineers to design new modules and refactor legacy areas.', 'Solid understanding of OOP, algorithms, and modern web architecture. Experience working in an Agile / Scrum delivery team. Track record of shipping production-quality software in collaborative teams. Strong communication skills in English and Vietnamese (written and spoken).', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Open-source contributions or technical writing.', 'Take-home assignment provided after the screening round.', 5, 1, 'active', '2026-04-09 05:00:00'),
(26, 2, 26, 11, 1, 12, 1, 2, 1, 6, NULL, 2, 8, 2, '13th month salary + performance bonus, premium health insurance for employee + family.', 'Build, ship and maintain user-facing features in close collaboration with design and product. Investigate production incidents and propose long-term improvements. Own the data pipeline from ingestion to visualisation, ensuring data quality. Drive the delivery of structured analytics dashboards for business stakeholders.', 'Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Strong communication skills in English and Vietnamese (written and spoken). Experience working in an Agile / Scrum delivery team.', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Experience with cloud platforms (AWS, GCP or Azure).', 'You will join a 6-person squad reporting to the Engineering Manager.', 1, 2, 'active', '2026-04-10 07:00:00'),
(27, 3, 3, 1, 1, 11, 2, 1, 3, 10, 31, 3, 9, 1, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Pair with senior engineers to design new modules and refactor legacy areas. Investigate production incidents and propose long-term improvements. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Own the data pipeline from ingestion to visualisation, ensuring data quality.', 'Track record of shipping production-quality software in collaborative teams. Solid understanding of OOP, algorithms, and modern web architecture. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Strong communication skills in English and Vietnamese (written and spoken).', 'A portfolio of shipped products or design case studies. Experience with cloud platforms (AWS, GCP or Azure).', 'Visa sponsorship considered for exceptional international candidates.', 2, 3, 'active', '2026-04-27 03:00:00'),
(28, 4, 10, 4, 1, 10, 3, 3, 1, 1, 5, 1, 1, 2, 'Equity / stock options for senior hires, paid parental leave, generous PTO.', 'Pair with senior engineers to design new modules and refactor legacy areas. Collaborate with marketing on multi-channel campaigns and performance tracking. Translate functional requirements into clean, well-tested code following the team coding standards. Participate in code reviews, sprint planning, retrospectives and on-call rotations.', 'Experience working in an Agile / Scrum delivery team. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Solid understanding of OOP, algorithms, and modern web architecture.', 'Experience with cloud platforms (AWS, GCP or Azure). Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'You will join a 6-person squad reporting to the Engineering Manager.', 3, 4, 'active', '2026-04-23 22:00:00'),
(29, 5, 17, 7, 1, 9, 4, 1, 1, 4, NULL, 2, 2, 1, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Own the data pipeline from ingestion to visualisation, ensuring data quality. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Pair with senior engineers to design new modules and refactor legacy areas. Drive the delivery of structured analytics dashboards for business stakeholders.', 'Experience working in an Agile / Scrum delivery team. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Solid understanding of OOP, algorithms, and modern web architecture. Track record of shipping production-quality software in collaborative teams.', 'A portfolio of shipped products or design case studies. Knowledge of Docker, Kubernetes or other container tooling.', 'Two technical interviews + final culture-fit conversation with the hiring manager.', 4, 5, 'active', '2026-04-25 11:00:00'),
(30, 6, 24, 10, 1, 8, 5, 3, 1, 6, 22, 3, 3, 2, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Build, ship and maintain user-facing features in close collaboration with design and product. Pair with senior engineers to design new modules and refactor legacy areas. Own the data pipeline from ingestion to visualisation, ensuring data quality. Participate in code reviews, sprint planning, retrospectives and on-call rotations.', 'Track record of shipping production-quality software in collaborative teams. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Solid understanding of OOP, algorithms, and modern web architecture.', 'A portfolio of shipped products or design case studies. Open-source contributions or technical writing.', 'Relocation support available for candidates outside the city.', 5, 6, 'active', '2026-04-29 15:00:00'),
(31, 7, 1, 13, 1, 7, 1, 2, 3, 11, NULL, 1, 4, 1, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Build, ship and maintain user-facing features in close collaboration with design and product. Investigate production incidents and propose long-term improvements. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Collaborate with marketing on multi-channel campaigns and performance tracking.', 'Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Track record of shipping production-quality software in collaborative teams.', 'Knowledge of Docker, Kubernetes or other container tooling. Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'You will join a 6-person squad reporting to the Engineering Manager.', 1, 1, 'active', '2026-04-13 14:00:00'),
(32, 8, 8, 3, 1, 6, 2, 5, 1, 5, 21, 2, 5, 2, 'English / Japanese language courses subsidised, flexible working hours.', 'Collaborate with marketing on multi-channel campaigns and performance tracking. Translate functional requirements into clean, well-tested code following the team coding standards. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Drive the delivery of structured analytics dashboards for business stakeholders.', 'Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Solid understanding of OOP, algorithms, and modern web architecture. Experience working in an Agile / Scrum delivery team. Strong communication skills in English and Vietnamese (written and spoken).', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Knowledge of Docker, Kubernetes or other container tooling.', 'You will join a 6-person squad reporting to the Engineering Manager.', 2, 2, 'active', '2026-04-06 14:00:00'),
(33, 9, 15, 6, 1, 5, 3, 1, 3, 10, 31, 3, 6, 1, 'Equity / stock options for senior hires, paid parental leave, generous PTO.', 'Translate functional requirements into clean, well-tested code following the team coding standards. Mentor junior engineers and contribute to internal engineering blogs. Build, ship and maintain user-facing features in close collaboration with design and product. Participate in code reviews, sprint planning, retrospectives and on-call rotations.', 'Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Strong communication skills in English and Vietnamese (written and spoken). Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL.', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). A portfolio of shipped products or design case studies.', 'Take-home assignment provided after the screening round.', 3, 3, 'active', '2026-04-24 01:00:00'),
(34, 10, 22, 9, 1, 4, 4, 3, 1, 6, 22, 1, 7, 2, 'English / Japanese language courses subsidised, flexible working hours.', 'Build, ship and maintain user-facing features in close collaboration with design and product. Translate functional requirements into clean, well-tested code following the team coding standards. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Investigate production incidents and propose long-term improvements.', 'Track record of shipping production-quality software in collaborative teams. Experience working in an Agile / Scrum delivery team. Solid understanding of OOP, algorithms, and modern web architecture. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience.', 'Knowledge of Docker, Kubernetes or other container tooling. Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'Two technical interviews + final culture-fit conversation with the hiring manager.', 4, 4, 'active', '2026-04-15 22:00:00'),
(35, 11, 29, 12, 1, 3, 5, 2, 1, 1, NULL, 2, 8, 1, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Participate in code reviews, sprint planning, retrospectives and on-call rotations. Investigate production incidents and propose long-term improvements. Own the data pipeline from ingestion to visualisation, ensuring data quality. Drive the delivery of structured analytics dashboards for business stakeholders.', 'Solid understanding of OOP, algorithms, and modern web architecture. Track record of shipping production-quality software in collaborative teams. Experience working in an Agile / Scrum delivery team. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience.', 'Experience with cloud platforms (AWS, GCP or Azure). A portfolio of shipped products or design case studies.', 'Take-home assignment provided after the screening round.', 5, 5, 'active', '2026-04-09 09:00:00'),
(36, 12, 6, 2, 1, 2, 1, 5, 1, 1, NULL, 3, 9, 2, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Translate functional requirements into clean, well-tested code following the team coding standards. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Collaborate with marketing on multi-channel campaigns and performance tracking. Own the data pipeline from ingestion to visualisation, ensuring data quality.', 'Experience working in an Agile / Scrum delivery team. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Track record of shipping production-quality software in collaborative teams. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience.', 'Open-source contributions or technical writing. Knowledge of Docker, Kubernetes or other container tooling.', 'Take-home assignment provided after the screening round.', 1, 6, 'active', '2026-04-09 13:00:00'),
(37, 1, 13, 5, 1, 1, 2, 5, 1, 5, 21, 1, 1, 1, 'Equity / stock options for senior hires, paid parental leave, generous PTO.', 'Translate functional requirements into clean, well-tested code following the team coding standards. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Mentor junior engineers and contribute to internal engineering blogs. Own the data pipeline from ingestion to visualisation, ensuring data quality.', 'Strong communication skills in English and Vietnamese (written and spoken). Solid understanding of OOP, algorithms, and modern web architecture. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience.', 'Knowledge of Docker, Kubernetes or other container tooling. A portfolio of shipped products or design case studies.', 'Two technical interviews + final culture-fit conversation with the hiring manager.', 2, 1, 'active', '2026-04-17 06:00:00'),
(38, 2, 20, 8, 1, 12, 3, 3, 1, 4, 19, 2, 2, 2, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Investigate production incidents and propose long-term improvements. Mentor junior engineers and contribute to internal engineering blogs. Collaborate with marketing on multi-channel campaigns and performance tracking. Pair with senior engineers to design new modules and refactor legacy areas.', 'Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Solid understanding of OOP, algorithms, and modern web architecture. Strong communication skills in English and Vietnamese (written and spoken). Experience working in an Agile / Scrum delivery team.', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Open-source contributions or technical writing.', 'You will join a 6-person squad reporting to the Engineering Manager.', 3, 2, 'active', '2026-04-19 17:00:00'),
(39, 3, 27, 11, 1, 11, 4, 1, 1, 2, 8, 3, 3, 1, '13th month salary + performance bonus, premium health insurance for employee + family.', 'Mentor junior engineers and contribute to internal engineering blogs. Drive the delivery of structured analytics dashboards for business stakeholders. Pair with senior engineers to design new modules and refactor legacy areas. Translate functional requirements into clean, well-tested code following the team coding standards.', 'Track record of shipping production-quality software in collaborative teams. Strong communication skills in English and Vietnamese (written and spoken). Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL.', 'Knowledge of Docker, Kubernetes or other container tooling. Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'Two technical interviews + final culture-fit conversation with the hiring manager.', 4, 3, 'active', '2026-04-02 13:00:00'),
(40, 4, 4, 1, 1, 10, 5, 2, 1, 4, 18, 1, 4, 2, '13th month salary + performance bonus, premium health insurance for employee + family.', 'Investigate production incidents and propose long-term improvements. Drive the delivery of structured analytics dashboards for business stakeholders. Build, ship and maintain user-facing features in close collaboration with design and product. Collaborate with marketing on multi-channel campaigns and performance tracking.', 'Experience working in an Agile / Scrum delivery team. Track record of shipping production-quality software in collaborative teams. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Familiarity with REST APIs, version control (Git), and CI/CD pipelines.', 'A portfolio of shipped products or design case studies. Knowledge of Docker, Kubernetes or other container tooling.', 'Take-home assignment provided after the screening round.', 5, 4, 'active', '2026-04-21 22:00:00'),
(41, 5, 11, 4, 1, 9, 1, 3, 1, 7, 23, 2, 5, 1, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Investigate production incidents and propose long-term improvements. Pair with senior engineers to design new modules and refactor legacy areas. Translate functional requirements into clean, well-tested code following the team coding standards. Build, ship and maintain user-facing features in close collaboration with design and product.', 'Strong communication skills in English and Vietnamese (written and spoken). Solid understanding of OOP, algorithms, and modern web architecture. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Familiarity with REST APIs, version control (Git), and CI/CD pipelines.', 'Open-source contributions or technical writing. Knowledge of Docker, Kubernetes or other container tooling.', 'Relocation support available for candidates outside the city.', 1, 5, 'active', '2026-04-14 15:00:00'),
(42, 6, 18, 7, 1, 8, 2, 2, 1, 3, 17, 3, 6, 2, 'Equity / stock options for senior hires, paid parental leave, generous PTO.', 'Translate functional requirements into clean, well-tested code following the team coding standards. Collaborate with marketing on multi-channel campaigns and performance tracking. Build, ship and maintain user-facing features in close collaboration with design and product. Participate in code reviews, sprint planning, retrospectives and on-call rotations.', 'Experience working in an Agile / Scrum delivery team. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Strong communication skills in English and Vietnamese (written and spoken). Solid understanding of OOP, algorithms, and modern web architecture.', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Knowledge of Docker, Kubernetes or other container tooling.', 'You will join a 6-person squad reporting to the Engineering Manager.', 2, 6, 'active', '2026-04-06 00:00:00'),
(43, 7, 25, 10, 1, 7, 3, 2, 1, 4, 19, 1, 7, 1, '13th month salary + performance bonus, premium health insurance for employee + family.', 'Mentor junior engineers and contribute to internal engineering blogs. Pair with senior engineers to design new modules and refactor legacy areas. Own the data pipeline from ingestion to visualisation, ensuring data quality. Translate functional requirements into clean, well-tested code following the team coding standards.', 'Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Strong communication skills in English and Vietnamese (written and spoken). Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Track record of shipping production-quality software in collaborative teams.', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Experience with cloud platforms (AWS, GCP or Azure).', 'You will join a 6-person squad reporting to the Engineering Manager.', 3, 1, 'active', '2026-04-25 09:00:00'),
(44, 8, 2, 13, 1, 6, 4, 5, 2, 8, 27, 2, 8, 2, 'Equity / stock options for senior hires, paid parental leave, generous PTO.', 'Own the data pipeline from ingestion to visualisation, ensuring data quality. Pair with senior engineers to design new modules and refactor legacy areas. Mentor junior engineers and contribute to internal engineering blogs. Investigate production incidents and propose long-term improvements.', 'Solid understanding of OOP, algorithms, and modern web architecture. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Strong communication skills in English and Vietnamese (written and spoken). Bachelor degree in Computer Science, Information Systems, or equivalent practical experience.', 'Experience with cloud platforms (AWS, GCP or Azure). Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'You will join a 6-person squad reporting to the Engineering Manager.', 4, 2, 'active', '2026-04-14 08:00:00'),
(45, 9, 9, 3, 1, 5, 5, 2, 3, 10, 30, 3, 9, 1, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Mentor junior engineers and contribute to internal engineering blogs. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Own the data pipeline from ingestion to visualisation, ensuring data quality. Translate functional requirements into clean, well-tested code following the team coding standards.', 'Solid understanding of OOP, algorithms, and modern web architecture. Strong communication skills in English and Vietnamese (written and spoken). Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Experience working in an Agile / Scrum delivery team.', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Open-source contributions or technical writing.', 'Relocation support available for candidates outside the city.', 5, 3, 'active', '2026-04-14 09:00:00'),
(46, 10, 16, 6, 1, 4, 1, 2, 3, 11, 32, 1, 1, 2, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Drive the delivery of structured analytics dashboards for business stakeholders. Investigate production incidents and propose long-term improvements. Collaborate with marketing on multi-channel campaigns and performance tracking. Mentor junior engineers and contribute to internal engineering blogs.', 'Experience working in an Agile / Scrum delivery team. Solid understanding of OOP, algorithms, and modern web architecture. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Track record of shipping production-quality software in collaborative teams.', 'Experience with cloud platforms (AWS, GCP or Azure). Knowledge of Docker, Kubernetes or other container tooling.', 'You will join a 6-person squad reporting to the Engineering Manager.', 1, 4, 'active', '2026-04-01 09:00:00'),
(47, 11, 23, 9, 1, 3, 2, 2, 5, 15, 38, 2, 2, 1, 'Equity / stock options for senior hires, paid parental leave, generous PTO.', 'Investigate production incidents and propose long-term improvements. Collaborate with marketing on multi-channel campaigns and performance tracking. Drive the delivery of structured analytics dashboards for business stakeholders. Pair with senior engineers to design new modules and refactor legacy areas.', 'Experience working in an Agile / Scrum delivery team. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Strong communication skills in English and Vietnamese (written and spoken).', 'Exposure to data warehousing tools (BigQuery, Snowflake, Redshift). Experience with cloud platforms (AWS, GCP or Azure).', 'Relocation support available for candidates outside the city.', 2, 5, 'active', '2026-04-11 23:00:00'),
(48, 12, 30, 12, 1, 2, 3, 5, 1, 7, 24, 3, 3, 2, 'Equity / stock options for senior hires, paid parental leave, generous PTO.', 'Pair with senior engineers to design new modules and refactor legacy areas. Collaborate with marketing on multi-channel campaigns and performance tracking. Translate functional requirements into clean, well-tested code following the team coding standards. Build, ship and maintain user-facing features in close collaboration with design and product.', 'Track record of shipping production-quality software in collaborative teams. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Strong communication skills in English and Vietnamese (written and spoken).', 'Experience with cloud platforms (AWS, GCP or Azure). A portfolio of shipped products or design case studies.', 'Two technical interviews + final culture-fit conversation with the hiring manager.', 3, 6, 'active', '2026-04-28 03:00:00'),
(49, 1, 7, 2, 1, 1, 4, 1, 2, 8, 27, 1, 4, 1, 'English / Japanese language courses subsidised, flexible working hours.', 'Collaborate with marketing on multi-channel campaigns and performance tracking. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Mentor junior engineers and contribute to internal engineering blogs. Investigate production incidents and propose long-term improvements.', 'Track record of shipping production-quality software in collaborative teams. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Experience working in an Agile / Scrum delivery team. Familiarity with REST APIs, version control (Git), and CI/CD pipelines.', 'Open-source contributions or technical writing. A portfolio of shipped products or design case studies.', 'Relocation support available for candidates outside the city.', 4, 1, 'active', '2026-04-19 01:00:00'),
(50, 2, 14, 5, 1, 12, 5, 1, 1, 3, 14, 2, 5, 2, '13th month salary + performance bonus, premium health insurance for employee + family.', 'Drive the delivery of structured analytics dashboards for business stakeholders. Build, ship and maintain user-facing features in close collaboration with design and product. Mentor junior engineers and contribute to internal engineering blogs. Participate in code reviews, sprint planning, retrospectives and on-call rotations.', 'Solid understanding of OOP, algorithms, and modern web architecture. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Experience working in an Agile / Scrum delivery team.', 'A portfolio of shipped products or design case studies. Experience with cloud platforms (AWS, GCP or Azure).', 'Visa sponsorship considered for exceptional international candidates.', 5, 2, 'active', '2026-04-28 10:00:00'),
(51, 3, 21, 8, 1, 11, 1, 1, 1, 5, 20, 3, 6, 1, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Mentor junior engineers and contribute to internal engineering blogs. Build, ship and maintain user-facing features in close collaboration with design and product. Own the data pipeline from ingestion to visualisation, ensuring data quality. Translate functional requirements into clean, well-tested code following the team coding standards.', 'Experience working in an Agile / Scrum delivery team. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Track record of shipping production-quality software in collaborative teams. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL.', 'Experience with cloud platforms (AWS, GCP or Azure). A portfolio of shipped products or design case studies.', 'Relocation support available for candidates outside the city.', 1, 3, 'active', '2026-04-12 07:00:00'),
(52, 4, 28, 11, 1, 10, 2, 2, 4, 13, NULL, 1, 7, 2, '13th month salary + performance bonus, premium health insurance for employee + family.', 'Own the data pipeline from ingestion to visualisation, ensuring data quality. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Drive the delivery of structured analytics dashboards for business stakeholders. Pair with senior engineers to design new modules and refactor legacy areas.', 'Track record of shipping production-quality software in collaborative teams. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Solid understanding of OOP, algorithms, and modern web architecture. Experience working in an Agile / Scrum delivery team.', 'Experience with cloud platforms (AWS, GCP or Azure). Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'You will join a 6-person squad reporting to the Engineering Manager.', 2, 4, 'active', '2026-04-13 15:00:00'),
(53, 5, 5, 1, 1, 9, 3, 2, 4, 13, NULL, 2, 8, 1, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Collaborate with marketing on multi-channel campaigns and performance tracking. Build, ship and maintain user-facing features in close collaboration with design and product. Pair with senior engineers to design new modules and refactor legacy areas. Drive the delivery of structured analytics dashboards for business stakeholders.', 'Track record of shipping production-quality software in collaborative teams. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Familiarity with REST APIs, version control (Git), and CI/CD pipelines.', 'Experience with cloud platforms (AWS, GCP or Azure). Open-source contributions or technical writing.', 'Two technical interviews + final culture-fit conversation with the hiring manager.', 3, 5, 'active', '2026-03-31 18:00:00'),
(54, 6, 12, 4, 1, 8, 4, 2, 4, 12, 34, 3, 9, 2, 'Annual company trip, monthly team-building budget, snack-stocked pantry.', 'Pair with senior engineers to design new modules and refactor legacy areas. Translate functional requirements into clean, well-tested code following the team coding standards. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Mentor junior engineers and contribute to internal engineering blogs.', 'Track record of shipping production-quality software in collaborative teams. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Strong communication skills in English and Vietnamese (written and spoken). Solid understanding of OOP, algorithms, and modern web architecture.', 'Experience with cloud platforms (AWS, GCP or Azure). Open-source contributions or technical writing.', 'Relocation support available for candidates outside the city.', 4, 6, 'active', '2026-04-02 20:00:00'),
(55, 7, 19, 7, 1, 7, 5, 1, 2, 8, 26, 1, 1, 1, 'Equity / stock options for senior hires, paid parental leave, generous PTO.', 'Own the data pipeline from ingestion to visualisation, ensuring data quality. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Collaborate with marketing on multi-channel campaigns and performance tracking. Pair with senior engineers to design new modules and refactor legacy areas.', 'Solid understanding of OOP, algorithms, and modern web architecture. Track record of shipping production-quality software in collaborative teams. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience.', 'Knowledge of Docker, Kubernetes or other container tooling. Experience with cloud platforms (AWS, GCP or Azure).', 'You will join a 6-person squad reporting to the Engineering Manager.', 5, 1, 'active', '2026-04-12 00:00:00'),
(56, 8, 26, 10, 1, 6, 1, 1, 1, 7, 23, 2, 2, 2, 'Macbook Pro provided, fully covered training budget, hybrid work option.', 'Translate functional requirements into clean, well-tested code following the team coding standards. Mentor junior engineers and contribute to internal engineering blogs. Participate in code reviews, sprint planning, retrospectives and on-call rotations. Drive the delivery of structured analytics dashboards for business stakeholders.', 'Experience working in an Agile / Scrum delivery team. Track record of shipping production-quality software in collaborative teams. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Solid understanding of OOP, algorithms, and modern web architecture.', 'Knowledge of Docker, Kubernetes or other container tooling. Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'Relocation support available for candidates outside the city.', 1, 2, 'active', '2026-04-01 00:00:00'),
(57, 9, 3, 13, 1, 5, 2, 5, 1, 6, 22, 3, 3, 1, 'English / Japanese language courses subsidised, flexible working hours.', 'Collaborate with marketing on multi-channel campaigns and performance tracking. Investigate production incidents and propose long-term improvements. Mentor junior engineers and contribute to internal engineering blogs. Pair with senior engineers to design new modules and refactor legacy areas.', 'Strong communication skills in English and Vietnamese (written and spoken). Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Track record of shipping production-quality software in collaborative teams. Solid understanding of OOP, algorithms, and modern web architecture.', 'A portfolio of shipped products or design case studies. Experience with cloud platforms (AWS, GCP or Azure).', 'Two technical interviews + final culture-fit conversation with the hiring manager.', 2, 3, 'removed', '2026-04-22 14:00:00'),
(58, 10, 10, 3, 1, 4, 3, 3, 1, 5, 21, 1, 4, 2, '13th month salary + performance bonus, premium health insurance for employee + family.', 'Own the data pipeline from ingestion to visualisation, ensuring data quality. Build, ship and maintain user-facing features in close collaboration with design and product. Mentor junior engineers and contribute to internal engineering blogs. Investigate production incidents and propose long-term improvements.', 'Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL. Bachelor degree in Computer Science, Information Systems, or equivalent practical experience. Track record of shipping production-quality software in collaborative teams. Experience working in an Agile / Scrum delivery team.', 'Open-source contributions or technical writing. Knowledge of Docker, Kubernetes or other container tooling.', 'Take-home assignment provided after the screening round.', 3, 4, 'removed', '2026-04-19 16:00:00'),
(59, 11, 17, 6, 1, 3, 4, 2, 1, 5, 20, 2, 5, 1, '13th month salary + performance bonus, premium health insurance for employee + family.', 'Investigate production incidents and propose long-term improvements. Pair with senior engineers to design new modules and refactor legacy areas. Drive the delivery of structured analytics dashboards for business stakeholders. Mentor junior engineers and contribute to internal engineering blogs.', 'Strong communication skills in English and Vietnamese (written and spoken). Experience working in an Agile / Scrum delivery team. Familiarity with REST APIs, version control (Git), and CI/CD pipelines. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL.', 'A portfolio of shipped products or design case studies. Open-source contributions or technical writing.', 'You will join a 6-person squad reporting to the Engineering Manager.', 4, 5, 'inactive', '2026-04-08 19:00:00'),
(60, 12, 24, 9, 1, 2, 5, 5, 3, 11, 32, 3, 6, 2, 'English / Japanese language courses subsidised, flexible working hours.', 'Drive the delivery of structured analytics dashboards for business stakeholders. Mentor junior engineers and contribute to internal engineering blogs. Pair with senior engineers to design new modules and refactor legacy areas. Translate functional requirements into clean, well-tested code following the team coding standards.', 'Experience working in an Agile / Scrum delivery team. Solid understanding of OOP, algorithms, and modern web architecture. Track record of shipping production-quality software in collaborative teams. Comfort working with relational databases (MySQL, PostgreSQL) and writing SQL.', 'A portfolio of shipped products or design case studies. Exposure to data warehousing tools (BigQuery, Snowflake, Redshift).', 'Two technical interviews + final culture-fit conversation with the hiring manager.', 5, 6, 'inactive', '2026-04-17 10:00:00');

-- Many-to-many required skills (max 5 per vacancy)
INSERT INTO job_vacancy_skills (job_vacancy_id, skill_id, proficiency_level_id) VALUES
(1, 14, 1),
(1, 32, 2),
(1, 46, 3),
(1, 53, 1),
(1, 18, 4),
(2, 44, 2),
(2, 24, 1),
(2, 5, 3),
(3, 46, 2),
(3, 3, 1),
(3, 40, 3),
(3, 54, 1),
(3, 12, 3),
(4, 9, 2),
(4, 36, 2),
(4, 43, 2),
(4, 12, 2),
(5, 40, 4),
(5, 17, 2),
(5, 55, 3),
(5, 46, 4),
(6, 17, 2),
(6, 11, 2),
(6, 37, 2),
(6, 47, 3),
(7, 18, 4),
(7, 44, 2),
(7, 47, 2),
(7, 53, 2),
(7, 20, 4),
(8, 10, 3),
(8, 36, 1),
(8, 22, 4),
(8, 19, 3),
(8, 46, 1),
(9, 13, 3),
(9, 52, 1),
(9, 40, 3),
(9, 4, 2),
(10, 23, 3),
(10, 17, 2),
(10, 38, 3),
(11, 25, 2),
(11, 45, 3),
(11, 8, 2),
(12, 35, 1),
(12, 41, 3),
(12, 55, 1),
(12, 56, 3),
(13, 39, 1),
(13, 28, 1),
(13, 15, 3),
(13, 3, 1),
(13, 34, 2),
(14, 52, 3),
(14, 9, 4),
(15, 7, 1),
(15, 26, 2),
(15, 21, 1),
(16, 44, 2),
(16, 3, 3),
(16, 19, 3),
(17, 8, 3),
(17, 29, 1),
(18, 11, 3),
(18, 53, 4),
(18, 8, 2),
(19, 28, 3),
(19, 38, 2),
(19, 7, 1),
(19, 16, 2),
(20, 5, 4),
(20, 19, 3),
(20, 15, 3),
(20, 47, 4),
(21, 27, 2),
(21, 9, 4),
(21, 45, 2),
(21, 25, 3),
(21, 26, 1),
(22, 26, 1),
(22, 53, 1),
(23, 2, 4),
(23, 14, 2),
(24, 43, 1),
(24, 41, 3),
(24, 44, 1),
(25, 46, 1),
(25, 3, 4),
(25, 31, 1),
(25, 32, 3),
(25, 45, 3),
(26, 22, 2),
(26, 32, 1),
(27, 52, 3),
(27, 12, 2),
(27, 53, 1),
(27, 11, 2),
(28, 55, 2),
(28, 40, 3),
(28, 13, 4),
(29, 43, 4),
(29, 25, 1),
(29, 47, 2),
(29, 41, 1),
(29, 15, 3),
(30, 50, 1),
(30, 45, 3),
(31, 23, 3),
(31, 44, 2),
(31, 31, 3),
(32, 56, 1),
(32, 4, 1),
(32, 17, 4),
(32, 38, 2),
(32, 5, 1),
(33, 52, 1),
(33, 14, 3),
(33, 35, 2),
(33, 45, 2),
(34, 49, 3),
(34, 11, 2),
(34, 27, 3),
(34, 13, 1),
(34, 54, 4),
(35, 23, 3),
(35, 11, 1),
(35, 34, 2),
(35, 12, 2),
(35, 35, 2),
(36, 9, 4),
(36, 33, 3),
(36, 13, 4),
(37, 36, 1),
(37, 14, 3),
(37, 12, 1),
(37, 53, 1),
(37, 30, 2),
(38, 32, 4),
(38, 47, 2),
(38, 36, 1),
(38, 48, 3),
(38, 10, 4),
(39, 22, 1),
(39, 32, 2),
(39, 15, 4),
(39, 5, 1),
(39, 2, 1),
(40, 54, 2),
(40, 22, 1),
(40, 24, 4),
(41, 15, 3),
(41, 50, 4),
(42, 17, 4),
(42, 32, 4),
(42, 55, 1),
(42, 10, 3),
(42, 14, 1),
(43, 13, 1),
(43, 29, 1),
(43, 54, 2),
(43, 35, 2),
(44, 24, 3),
(44, 7, 1),
(45, 43, 2),
(45, 20, 4),
(45, 16, 4),
(46, 29, 1),
(46, 54, 1),
(46, 23, 4),
(46, 35, 2),
(46, 9, 1),
(47, 8, 4),
(47, 30, 4),
(47, 6, 4),
(48, 15, 2),
(48, 31, 3),
(48, 45, 2),
(48, 54, 2),
(48, 33, 3),
(49, 12, 2),
(49, 13, 4),
(49, 21, 2),
(50, 53, 1),
(50, 20, 3),
(50, 9, 4),
(51, 8, 4),
(51, 19, 1),
(51, 5, 2),
(52, 32, 4),
(52, 1, 2),
(53, 30, 4),
(53, 11, 1),
(53, 50, 3),
(53, 28, 1),
(54, 41, 1),
(54, 22, 2),
(54, 33, 1),
(55, 40, 4),
(55, 41, 4),
(55, 47, 2),
(55, 49, 1),
(55, 16, 1),
(56, 32, 4),
(56, 23, 1),
(56, 43, 4),
(56, 5, 1),
(56, 29, 2),
(57, 55, 3),
(57, 5, 4),
(58, 45, 4),
(58, 11, 2),
(58, 17, 3),
(59, 32, 1),
(59, 28, 1),
(60, 14, 1),
(60, 3, 2),
(60, 33, 1),
(60, 49, 4);

