<?php
function currentLang() {
    $lang = $_SESSION['lang'] ?? 'en';
    return in_array($lang, ['en', 'vi'], true) ? $lang : 'en';
}

function langUrl($lang) {
    $params = $_GET;
    $params['lang'] = $lang;
    $params['return'] = $_SERVER['REQUEST_URI'] ?? BASE_URL . '/index.php?page=home';
    return url('set_language', $params);
}

function t($key) {
    static $translations = [
        'en' => [
            'home' => 'Home',
            'brand_tagline' => 'Find better talent',
            'dashboard' => 'Dashboard',
            'login' => 'Login',
            'logout' => 'Logout',
            'register' => 'Register',
            'create_account' => 'Create Account',
            'language' => 'Language',
            'english' => 'English',
            'vietnamese' => 'Tiếng Việt',
            'hero_eyebrow' => 'Job Vacancy Management & Search System',
            'hero_title' => 'Phase 1 foundation for a structured job portal.',
            'hero_intro' => 'Built with PHP, MySQL, HTML, CSS, and JavaScript following the assignment folder structure: public entry point, app logic, config database settings, and assets under public.',
            'implemented_phase1' => 'Implemented in Phase 1',
            'item_structure' => 'MVC-like project structure',
            'item_database' => 'Database schema and seed data',
            'item_auth' => 'Register, login, logout',
            'item_roles' => 'Employer and job seeker registration',
            'item_admin' => 'Seeded admin account',
            'item_redirects' => 'Role-based dashboard redirects',
            'constraints' => 'Assignment constraints',
            'scope_title' => 'Scope preserved from the PDFs',
            'normalized_data' => 'Normalized Data',
            'normalized_data_text' => 'The schema uses lookup tables for selectable job fields and separates structured location data.',
            'role_access' => 'Role-Based Access',
            'role_access_text' => 'Admin, employer, and job seeker accounts redirect to their own protected dashboard shell.',
            'no_out_scope' => 'No Out-of-Scope Workflows',
            'no_out_scope_text' => 'No CV creation, CV search, job application, recommendation, chat, or payment workflow is included.',
            'footer_desc' => 'Structured job vacancy management foundation for employers, job seekers, and administrators.',
            'phase1' => 'Phase 1',
            'scope_rules' => 'Scope Rules',
            'scope_rules_text' => 'No CV creation, CV search, job application, or matching workflow.',
            'welcome_back' => 'Welcome back',
            'login_intro' => 'Login to continue to your protected role dashboard.',
            'secure_password' => 'Secure password verification',
            'session_auth' => 'Session-based authentication',
            'role_redirect' => 'Role-based redirect after login',
            'email' => 'Email',
            'password' => 'Password',
            'no_account' => 'No account yet?',
            'create_your_account' => 'Create your account',
            'register_intro' => 'Phase 1 supports employer and job seeker registration. Admin accounts are created from seed data only.',
            'company_validation' => 'Employer company name validation',
            'email_unique' => 'Email uniqueness validation',
            'password_hashing' => 'Password hashing with PHP',
            'account_type' => 'Account Type',
            'employer' => 'Employer',
            'job_seeker' => 'Job Seeker',
            'full_name' => 'Full Name',
            'company_name' => 'Company Name',
            'confirm_password' => 'Confirm Password',
            'already_account' => 'Already have an account?',
            'admin_dashboard' => 'Admin Dashboard',
            'employer_dashboard' => 'Employer Dashboard',
            'job_seeker_dashboard' => 'Job Seeker Dashboard',
            'dashboard_subtitle' => 'Phase 1 foundation: authentication, role guards, base layout, and UI shell.',
            'back_to_site' => 'Back to Site',
            'admin_shell_title' => 'Admin dashboard shell',
            'admin_shell_text' => 'This protected page verifies the Phase 1 admin role guard and layout. Admin job moderation and lookup management belong to Phase 4 and are intentionally not built yet.',
            'employer_shell_title' => 'Employer dashboard shell',
            'employer_shell_text' => 'This protected page verifies employer registration, login, role redirect, and access control. Job vacancy creation and management belong to Phase 2 and are intentionally not built yet.',
            'job_seeker_shell_title' => 'Job seeker dashboard shell',
            'job_seeker_shell_text' => 'This protected page verifies job seeker registration, login, role redirect, and access control. Public search, filtering, sorting, and job detail pages belong to Phase 3 and are intentionally not built yet.',
            'admin_phase_note' => 'Phase 4 admin management is intentionally not implemented yet.',
            'employer_phase_note' => 'Phase 2 job CRUD is intentionally not implemented yet.',
            'job_seeker_phase_note' => 'Phase 3 job search is intentionally not implemented yet.',
        ],
        'vi' => [
            'home' => 'Trang chủ',
            'brand_tagline' => 'Tìm nhân tài tốt hơn',
            'dashboard' => 'Bảng điều khiển',
            'login' => 'Đăng nhập',
            'logout' => 'Đăng xuất',
            'register' => 'Đăng ký',
            'create_account' => 'Tạo tài khoản',
            'language' => 'Ngôn ngữ',
            'english' => 'English',
            'vietnamese' => 'Tiếng Việt',
            'hero_eyebrow' => 'Hệ thống quản lý và tìm kiếm việc làm',
            'hero_title' => 'Nền tảng Phase 1 cho hệ thống tuyển dụng có cấu trúc.',
            'hero_intro' => 'Xây dựng bằng PHP, MySQL, HTML, CSS và JavaScript theo cấu trúc bài yêu cầu: public là entry point, app chứa logic, config chứa cấu hình database, assets nằm trong public.',
            'implemented_phase1' => 'Đã hoàn thành trong Phase 1',
            'item_structure' => 'Cấu trúc MVC-like',
            'item_database' => 'Schema database và seed data',
            'item_auth' => 'Đăng ký, đăng nhập, đăng xuất',
            'item_roles' => 'Đăng ký Employer và Job Seeker',
            'item_admin' => 'Tài khoản admin seed sẵn',
            'item_redirects' => 'Điều hướng dashboard theo role',
            'constraints' => 'Ràng buộc bài làm',
            'scope_title' => 'Giữ đúng phạm vi theo 2 file PDF',
            'normalized_data' => 'Dữ liệu chuẩn hóa',
            'normalized_data_text' => 'Schema dùng lookup tables cho các trường chọn và tách riêng dữ liệu địa điểm có cấu trúc.',
            'role_access' => 'Phân quyền theo vai trò',
            'role_access_text' => 'Tài khoản admin, employer và job seeker được điều hướng tới dashboard bảo vệ theo đúng role.',
            'no_out_scope' => 'Không làm chức năng ngoài phạm vi',
            'no_out_scope_text' => 'Không có tạo CV, tìm kiếm CV, ứng tuyển, gợi ý, chat hoặc thanh toán.',
            'footer_desc' => 'Nền tảng quản lý tin tuyển dụng có cấu trúc cho employer, job seeker và administrator.',
            'phase1' => 'Phase 1',
            'scope_rules' => 'Quy tắc phạm vi',
            'scope_rules_text' => 'Không tạo CV, không tìm CV, không ứng tuyển và không matching workflow.',
            'welcome_back' => 'Chào mừng trở lại',
            'login_intro' => 'Đăng nhập để vào dashboard được bảo vệ theo vai trò.',
            'secure_password' => 'Xác thực mật khẩu an toàn',
            'session_auth' => 'Xác thực bằng session',
            'role_redirect' => 'Điều hướng theo role sau đăng nhập',
            'email' => 'Email',
            'password' => 'Mật khẩu',
            'no_account' => 'Chưa có tài khoản?',
            'create_your_account' => 'Tạo tài khoản',
            'register_intro' => 'Phase 1 hỗ trợ đăng ký employer và job seeker. Tài khoản admin chỉ được tạo bằng seed data.',
            'company_validation' => 'Kiểm tra tên công ty cho employer',
            'email_unique' => 'Kiểm tra email không trùng',
            'password_hashing' => 'Hash mật khẩu bằng PHP',
            'account_type' => 'Loại tài khoản',
            'employer' => 'Nhà tuyển dụng',
            'job_seeker' => 'Người tìm việc',
            'full_name' => 'Họ và tên',
            'company_name' => 'Tên công ty',
            'confirm_password' => 'Xác nhận mật khẩu',
            'already_account' => 'Đã có tài khoản?',
            'admin_dashboard' => 'Dashboard Admin',
            'employer_dashboard' => 'Dashboard Employer',
            'job_seeker_dashboard' => 'Dashboard Job Seeker',
            'dashboard_subtitle' => 'Nền tảng Phase 1: authentication, role guard, base layout và UI shell.',
            'back_to_site' => 'Quay lại website',
            'admin_shell_title' => 'Khung dashboard Admin',
            'admin_shell_text' => 'Trang bảo vệ này kiểm tra role guard và layout cho admin ở Phase 1. Quản lý job và lookup thuộc Phase 4 nên chưa triển khai.',
            'employer_shell_title' => 'Khung dashboard Employer',
            'employer_shell_text' => 'Trang bảo vệ này kiểm tra đăng ký, đăng nhập, điều hướng role và phân quyền cho employer. Tạo và quản lý job thuộc Phase 2 nên chưa triển khai.',
            'job_seeker_shell_title' => 'Khung dashboard Job Seeker',
            'job_seeker_shell_text' => 'Trang bảo vệ này kiểm tra đăng ký, đăng nhập, điều hướng role và phân quyền cho job seeker. Tìm kiếm, lọc, sắp xếp và xem chi tiết job thuộc Phase 3 nên chưa triển khai.',
            'admin_phase_note' => 'Quản lý admin thuộc Phase 4 nên chưa triển khai.',
            'employer_phase_note' => 'CRUD job thuộc Phase 2 nên chưa triển khai.',
            'job_seeker_phase_note' => 'Tìm kiếm job thuộc Phase 3 nên chưa triển khai.',
        ],
    ];

    $lang = currentLang();
    return $translations[$lang][$key] ?? $translations['en'][$key] ?? $key;
}
